name: Build master

on: [push, pull_request]

jobs:
  build:

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        dotnet: [3.0.100]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@bb95ce727fd49ec1a65933419cc7c91747785302
      with:
        dotnet-version: ${{ matrix.dotnet }}
    - name: Install local tools
      run: dotnet tool restore
    - name: Paket restore
      run: dotnet paket restore
    - name: Build
      run: dotnet fake run build.fsx
      env:
        CI: true
    - name: "trigger fantomas-ui pipeline"
      if: matrix.os == 'ubuntu-latest' && github.ref == 'refs/heads/master'
      run: curl -X POST -F token=${{secrets.FANTOMAS_UI_TOKEN}} -F ref=preview -F "variables[TRIGGER]=true" https://gitlab.com/api/v4/projects/8920076/trigger/pipeline
    - name: "trigger fantomas-ui preview-ng pipeline"
      if: matrix.os == 'ubuntu-latest' && github.ref == 'refs/heads/trivia'
      run: curl -X POST -F token=${{secrets.FANTOMAS_UI_TOKEN}} -F ref=preview-ng -F "variables[TRIGGER]=true" https://gitlab.com/api/v4/projects/8920076/trigger/pipeline
